<?php

namespace Tests\Domain\Shared;

use App\Exceptions\InvalidDocumentException;
use App\Domain\Shared\ValueObjects\Document;
use Tests\TestCase;

/**
 * Class DocumentTest
 * @package Tests\Domain\Shared
 * @author Rafael Neris <rafaelnerisdj@gmail.com>
 */
class DocumentTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDocument()
    {
        $document = new Document('53.119.152/0001-74');
        $type = $document->getType();
        $this->assertInstanceOf(Document::class, $document);
        $this->assertEquals('cnpj', $type);
    }

    public function testInvalidDocument()
    {
        $this->expectException(InvalidDocumentException::class);
        $document = new Document('32323233');
        $this->assertInstanceOf(Document::class, $document);
    }
}
