<?php

namespace Tests\Domain\Shared;

use App\Exceptions\InvalidEmailException;
use App\Domain\Shared\ValueObjects\Email;
use Tests\TestCase;

class EmailTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testConstructorWithInvalidEmail()
    {
        $this->expectException(InvalidEmailException::class);
        $email = new Email('2321303023023');
    }
}
